// ============================================================
//  tools/mcp/engine.mjs —— the engine capabilities the MCP server needs
//
//  Key fact: **validation and layout are pure JS and need no browser**.
//  So without a screenshot an agent can still ask: does the JSON pass, how large is
//  the content, which orientation should be used, whether it fits. The only
//  thing that truly needs a browser is that last look at whether it is good-looking.
//
//  This layer only does "given JSON, return facts"; it never generates JSON —
//  the engine does not generate JSON, that is the agent's job.
// ============================================================

import { existsSync, readFileSync, readdirSync, statSync } from 'node:fs'
import { join } from 'node:path'

import { renderToFile, REPO } from '../lib/make-html.mjs'
import { knowledgeOf, listKnowledgeTypes } from '../../src/core/registry.js'
// Registers the knowledge for each type (pure JS, no components). With it, validation
// and layout both come from the registry.
import '../../src/renderers/index.js'
import { tEn } from '../../src/core/i18n.js'

// The repository root is provided once by tools/lib/make-html.mjs (the server may be
// started from any cwd, so everything resolves relative to that location); this uses
// the REPO it exports directly.

// validate / notesOf / layoutReport / formatLayoutReport and the texts built from them live in
// tools/lib/report.mjs: the command line in the skill (tools/cli/) gives the agent the same words.
export { CANVAS, validate, notesOf, layoutReport, formatLayoutReport } from '../lib/report.mjs'

/**
 * Generate the self-contained HTML.
 *
 * There is only one implementation, in tools/lib/make-html.mjs — both the command-line
 * tool and this call it. There used to be one copy in each of two files (83% similar),
 * and changing one and forgetting the other showed up as "the HTML generated by one
 * path is wrong".
 */
export function renderHtml(spec, { outPath, preset } = {}) {
  return renderToFile(spec, { outPath, preset, quiet: true })
}

/**
 * The example list. Two batches for two readers: agent (examples/agent/*.json —
 * minimal, one idea each, must pass validation) and real (examples/*.json — real cases,
 * complete but long). The agent batch is the default.
 */
/**
 * The language suffix in an example file name.
 *
 * Examples are stored in pairs, `<name>.en.json` and `<name>.zh-CN.json`, same structure,
 * only the text values differ. English is the default, so an agent is listed **the
 * English copy only**: listing both shows one case twice and invites a wrong pick.
 */
const LANG_SUFFIX = /\.(en|zh-CN)\.json$/i

/** The Chinese variant (to be excluded). Old files with no suffix still count: they are small examples with Chinese content. */
const isZhVariant = (f) => /\.zh-CN\.json$/i.test(f)

export function listExamples({ type = 'fact', group = 'agent', lang = 'en' } = {}) {
  const dir = join(REPO, 'examples')
  // The size of each example is counted by its own type (knowledge.summarize): a procedure
  // listed with fact's counters used to read "0 events / 0 time slots"
  const read = (path, file) => {
    const spec = JSON.parse(readFileSync(path, 'utf8'))
    return {
      file,
      path,
      title: spec.title,
      bytes: readFileSync(path).length,
      ...(knowledgeOf(spec.type)?.summarize?.(spec) ?? { line: '' }),
    }
  }
  const jsonIn = (d, prefix) =>
    existsSync(d)
      ? readdirSync(d)
          .filter((f) => f.endsWith('.json'))
          // List only the current language: the zh variant does not appear in en mode and vice versa.
          // Old files with no language suffix are listed in both modes (they are not paired yet).
          .filter((f) => !LANG_SUFFIX.test(f) || (lang === 'zh' ? isZhVariant(f) : !isZhVariant(f)))
          .sort()
          .map((f) => read(join(d, f), `${prefix}${f}`))
      : []

  // Small examples are filed by type: examples/agent/<type>/*.json
  if (group === 'raw') {
    // Raw material: **do not** use it as a template when writing data; it is the source
    // from which "how these examples were made" is derived
    const rawDir = join(dir, 'raw')
    return existsSync(rawDir)
      ? readdirSync(rawDir)
          .filter((f) => f.endsWith('.md'))
          .sort()
          .map((f) => ({ file: `examples/raw/${f}`, path: join(rawDir, f), bytes: statSync(join(rawDir, f)).size }))
      : []
  }
  // Real cases are also filed by type: examples/<type>/*.json
  if (group === 'real') return jsonIn(join(dir, String(type)), `examples/${type}/`)
  return jsonIn(join(dir, 'agent', String(type)), `examples/agent/${type}/`)
}

/**
 * Read the full content of one example. **Only three kinds are recognised**:
 * examples/agent/*.json, examples/*.json and examples/raw/*.md. Anything else (for
 * example examples/README.md) counts as "not found".
 *
 * Why the restriction: `file` used to reach any file under examples, so an agent
 * thinking it was fetching an example got back a whole judgment. That is source
 * material, not an example; the caller must say what it wants to read.
 */
export function readExample(file, { lang = 'en' } = {}) {
  // Both forms are accepted: a relative path (examples/fact/x.json) and an absolute
  // path. The absolute form is indispensable: listExamples returns absolute paths, and
  // an agent copying one back must be able to fetch it (this used to accept only
  // relative paths, so it could not).
  const rel = String(file)
    .replace(/^examples\//, '')
    .replace(new RegExp(`^${REPO.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}/examples/`), '')
  // Three kinds of path: agent examples, real cases (filed by type, e.g.
  // examples/fact/x.json), raw material. The real-case kind used to be missing the
  // "type directory" level, so the paths listExamples(group:'real') returned could not
  // be fetched by readExample (a pre-existing bug).
  const ok =
    /^agent\/[\w-]+\/[\w.-]+\.json$/.test(rel) ||
    /^[\w-]+\/[\w.-]+\.json$/.test(rel) ||
    /^[\w.\u4e00-\u9fff-]+\.json$/.test(rel) ||
    /^raw\/[\w.\u4e00-\u9fff-]+\.md$/.test(rel)
  if (!ok) return null

  let p = join(REPO, 'examples', rel)
  // Paired examples: given the base name (e.g. xxx.json), resolve to the current
  // language's copy, so an agent need not know how the files are paired and can just
  // fetch the path antu_examples listed.
  if (!existsSync(p) && lang === 'en' && rel.endsWith('.json')) {
    const paired = p.replace(/\.json$/i, '.en.json')
    if (existsSync(paired)) p = paired
  }
  if (!existsSync(p)) return null
  return { path: p, text: readFileSync(p, 'utf8') }
}

/**
 * The spec list for an agent; scans only `spec/agent/`.
 *
 * The layer above, `spec/*.md`, is design documentation (it explains "why this was
 * decided at the time", tens of thousands of characters per file) and is
 * **not included here**: that is for humans, and serving it to an agent only burns
 * context. The division between the two is written in spec/agent/README.md.
 */
export function listAgentGuides() {
  const dir = join(REPO, 'spec/agent')
  return existsSync(dir)
    ? readdirSync(dir, { withFileTypes: true })
        .filter((e) => e.isDirectory() && existsSync(join(dir, e.name, 'guide.md')))
        .map((e) => e.name)
        .sort()
    : []
}

/**
 * Fetch the mechanism notes for one type.
 * One per type: spec/agent/<type>/guide.md. Adding a type means adding a directory.
 */
export function readAgentGuide(type = 'fact') {
  const p = join(REPO, 'spec/agent', String(type), 'guide.md')
  return existsSync(p) ? readFileSync(p, 'utf8') : null
}

/** The default assumption for canvas size (used when MCP reports the "fit zoom") */
export { listKnowledgeTypes }

/**
 * The field table, **fetched by type**.
 *
 * This used to call describeFactSchema() directly, which amounts to hard-coding fact
 * into the tool: once the relationship diagram exists, that whole path needs rework.
 * Now it comes from the registry, and adding a type changes not one line of the tools.
 */
export function describeSchema(type = 'fact') {
  const k = knowledgeOf(type)
  if (!k) return { ok: false, reason: unknownType(type) }
  return { ok: true, text: k.describe() }
}

/** The wording used consistently when reporting "the type you asked for does not exist yet" */
function unknownType(type) {
  const known = listKnowledgeTypes()
  const list = known.map((t) => `${t.type} (${tEn(t.labelKey)})`).join(', ')
  return `no reference material for type "${type}" yet. Available: ${list || '(none)'}.`
}
